### ISSUE TITLE
Pubsub error unregistered_route

### ISSUE THREAD

**Issue by alok102singh** [processone/ejabberd#1458]
> What version of ejabberd are you using?

16.12.23

> What operating system (version) are you using?

linux 16.04

> How did you install ejabberd (source, package, distribution)?
source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

i run the ejabberd 16.09. it is working fine, but as i cannot use "allow_subscription" in muc room. i update my ejabberd to 16.12.23 lastest pull from github (https://github.com/processone/ejabberd). but as i run the server i am getting a error on pubsub.

```
1:22:43.592 [error] {{unregistered_route,<<"pubsub.chat.eazespot.com">>},
[{ejabberd_router,host_of_route,1,[{file,"src/ejabberd_router.erl"},{line,253}]},
{mod_pubsub,plugin,2,[{file,"src/mod_pubsub.erl"},{line,3453}]},
{mod_pubsub,plugin_features,2,[{file,"src/mod_pubsub.erl"},{line,3541}]},
{mod_pubsub,'-features/2-fun-0-',3,[{file,"src/mod_pubsub.erl"},{line,3550}]},
{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},
{mod_pubsub,features,2,[{file,"src/mod_pubsub.erl"},{line,3549}]},
{mod_pubsub,disco_local_features,5,[{file,"src/mod_pubsub.erl"},{line,534}]},
{ejabberd_hooks,safe_apply,3,[{file,"src/ejabberd_hooks.erl"},{line,382}]}]}
running hook: {disco_local_features,
[{jid,<<>>,<<"chat.eazespot.com">>,<<>>,<<>>,<<"chat.eazespot.com">>,<<>>},
{jid,<<>>,<<"chat.eazespot.com">>,<<>>,<<>>,<<"chat.eazespot.com">>,<<>>},<<>>,<<>>]}
```

and also this one
```
11:22:27.714 [error] Error in process <0.556.0> on node 'ejabberd@172.31.17.63'
 with exit value:
 {function_clause,[{lists,foreach,[#Fun<mod_pubsub.19.68458034>,undefined],
 [{file,"lists.erl"},{line,1337}]},
 {mod_pubsub,send_loop,1,[{file,"src/mod_pubsub.erl"},{line,434}]}]}
```

i have done clustering also between 2 server. Can you help me in getting the error resolve
i have also found two entry in my database(psql):
` eazevent_chat=> select * from pubsub_node where host='pubsub.chat.eazespot.com';`
` host           |          node           | parent | type | nodeid `
` --------------------------+-------------------------+--------+------+--------`
` pubsub.chat.eazespot.com | /home                   |        | flat |    493`
` pubsub.chat.eazespot.com | /home/chat.eazespot.com |        | flat |    494`
` (2 rows) `

**Comment by cromain** [comment]
unregistered_route is consequence of pubsub being stopped.
I assume it was working for you in 16.09 and you did not changed config.
in your case, what is output of this command

`mod_pubsub:node_action(<<"pubsub.chat.eazespot.com">>,<<"flat">>, get_entity_subscriptions_for_send_last, [<<"pubsub.chat.eazespot.com">>,jid:make(<<>>,<<"chat.eazespot.com">>]).`

**Comment by alok102singh** [comment]
yeah it was working for me on 16.09. 

`--------------------------------------------------------------------
To bypass permanently this warning, add to ejabberdctl.cfg the line:
  EJABBERD_BYPASS_WARNINGS=true
Press return to continue


Erlang/OTP 19 [erts-8.1] [source] [64-bit] [async-threads:10] [kernel-poll:true]

Eshell V8.1  (abort with ^G)
(ejabberd@172.31.17.63)1> mod_pubsub:node_action(<<"pubsub.chat.eazespot.com">>,<<"flat">>, get_entity_subscriptions_for_send_last, [<<"pubsub.chat.eazespot.com">>,jid:make(<<>>,<<"chat.eazespot.com">>)]).

** exception error: {unregistered_route,<<"pubsub.chat.eazespot.com">>}
     in function  ejabberd_router:host_of_route/1 (src/ejabberd_router.erl, line 253)
     in call from mod_pubsub:transaction/3 (src/mod_pubsub.erl, line 3636)
(ejabberd@172.31.17.63)2> `

**Comment by alok102singh** [comment]
earlier my config for mod_muc was:

`  mod_muc:
    host: "chatrooms.@HOST@"
    access:
       - allow `

is this causing error now?

**Comment by alok102singh** [comment]
any update for me ? My server is giving error due to this.

**Comment by alok102singh** [comment]
i did checkout to 
` git checkout 08d482b064d2da57fb84e233caf858d63366f05a` to this commit "Allow old-stype mod_vcard_ldap in the config (#1410)". 

 Error stop occurring, but offline messages  are not delivering when user get back online.

**Comment by zinid** [comment]
This bug is fixed in `new_stream` branch, I will port it to `master.

**Comment by alok102singh** [comment]
I have delete all previous file. update my source code to latest `HEAD`.  And reinstall it again with all step.
Still occurring same error.

**Comment by zinid** [comment]
Same what? Pubsub related or offline related?

**Comment by alok102singh** [comment]
pubsub related.

**Comment by zinid** [comment]
Is there something in `crash.log`?

**Comment by alok102singh** [comment]
` 2017-01-14 15:02:45 =CRASH REPORT====
  crasher:
    initial call: mod_pubsub:init/1
    pid: <0.413.0>
    registered_name: []
    exception exit: {{aborted,{no_exists,pubsub_node,attributes}},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,352}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [ejabberd_sup,<0.61.0>]
    messages: []
    links: [<0.277.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 1514
  neighbours:
2017-01-14 15:07:50 =ERROR REPORT====
Error in process <0.791.0> on node 'ejabberd@172.31.20.208' with exit value:
{function_clause,[{lists,foreach,[#Fun<mod_pubsub.19.68458034>,undefined],[{file,"lists.erl"},{line,1337}]},{mod_pubsub,send_loop,1,[{file,"src/mod_pubsub.erl"},{line,434}]}]}`

**Comment by zinid** [comment]
Do you have the first crash everytime you restart the server?

**Comment by zeropopular** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mrniceguyzero@gmail.com
    Domain thezeroworld.com has exceeded the max emails per hour (7/7 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:36885)
	by node87.certushost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-7f84-zero=thezeroworld.com@sgmail.github.com>)
	id 1cSQJH-0005pA-9S
	for zero@thezeroworld.com; Sat, 14 Jan 2017 10:32:04 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=QJKdxYBUr1ZYfTFPdf6yxd/e/Ro=; b=Z35LwicinO/s265l
	jrVvlP58cAtyxtdx3rGpDFiQ8zBgNi5tfJEbdrK/7gVOhLnYpauCgExsz2VZs7ur
	QOW44NZCP2Hi8p2ZUp9gK7ad+nQMgITY48vRYfqjUZ+CL5rVkJ1vzIgRl73fACTJ
	WLuM2CihJ/khX+eeI7m4ZOkqZg4=
Received: by filter0423p1mdw1.sendgrid.net with SMTP id filter0423p1mdw1-20206-587A4419-24
        2017-01-14 15:30:33.212640032 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id TSYUKU56Tg-l23zgJORW6A
	for <zero@thezeroworld.com>; Sat, 14 Jan 2017 15:30:33.145 +0000 (UTC)
Date: Sat, 14 Jan 2017 07:30:33 -0800

**Comment by alok102singh** [comment]
I think this error occur when user try to get the muc room and history  and whenever a user get logged in my server.

```
 {{unregistered_route,<<"pubsub.chat.eazespot.com">>},[{ejabberd_router,host_of_route,1,[{file,"src/ejabberd_router.erl"},{line,253}]},{mod_pubsub,plugin,2,[{file,"src/mod_pubsub.erl"},{line,3453}]},{mod_pubsub,plugin_features,2,[{file,"src/mod_pubsub.erl"},{line,3541}]},{mod_pubsub,'-features/2-fun-0-',3,[{file,"src/mod_pubsub.erl"},{line,3550}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{mod_pubsub,features,2,[{file,"src/mod_pubsub.erl"},{line,3549}]},{mod_pubsub,disco_local_features,5,[{file,"src/mod_pubsub.erl"},{line,534}]},{ejabberd_hooks,safe_apply,3,[{file,"src/ejabberd_hooks.erl"},{line,382}]}]}
running hook: {disco_local_features,[{jid,<<>>,<<"chat.eazespot.com">>,<<>>,<<>>,<<"chat.eazespot.com">>,<<>>},{jid,<<>>,<<"chat.eazespot.com">>,<<>>,<<>>,<<"chat.eazespot.com">>,<<>>},<<>>,<<>>]}
```

**Comment by zinid** [comment]
I might be wrong since I'm not the author of pubsub code, but I think this is a consequence. The real problem is that crash with `{{aborted,{no_exists,pubsub_node,attributes}}` stuff. It means mnesia table `pubsub_node` doesn't exist, but seems like you have sql configured for your host, so I'm failing to understand why this error occurs. Maybe a configuration error?

**Comment by zinid** [comment]
I think @chris will get the problem, but he is AFK till Monday.

**Comment by zinid** [comment]
How many virtual hosts do you have configured? That's the value of `hosts` option.

**Comment by cromain** [comment]
for now, i can not reproduce this issue. will try again several different scenarios with pubsub using sql or mnesia.
I've fixed another bug with index init on mnesia table. side effect of this bug could produce errors like this pubsub one. If you have configured pubsub to use mnesia table, this previous fix should have fixed it already. I think it's worth checking latest HEAD anyway.
please copy your exact mod_pubsub config, i'll still try to reproduce it.

**Comment by cromain** [comment]
I reproduced the issue and found the corresponding bug. fix will be pushed by tomorrow.

**Comment by alok102singh** [comment]
Thanks. I couldn't reply as i was out of city.
