### ISSUE TITLE
ACL only for IPv4 localhost in default config or IPv4 addresses in IPv6 notation

### ISSUE THREAD

**Issue by moneytoo** [processone/ejabberd#1769]
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

CentOS 7.3

> How did you install ejabberd (source, package, distribution)?

The 1st party rpm: ejabberd-17.04-0.x86_64.rpm

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

With the default ejabberd config, ACL prevents me from running any privileged actions that are allowed on localhost.
On one hand ejabberd listens on both IPv4 & IPv6, thanks to ``ip: "::"``, but on the other, admin ACL is specified only for IPv4 localhost in ``- ip: "127.0.0.1/8"``. 

``/etc/hosts`` on CentOS 7.3 looks like this:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```
But that's ok as using 127.0.0.1 alone (in tsung: ``<server host='127.0.0.1' port='5222' type='tcp'/>``) also doesn't work. As IPv6 is prioritized over IPv4, ejabberd logs a following connection:
```
[info] <0.349.0>@ejabberd_listener:accept:311 (<0.527.0>) Accepted connection ::FFFF:127.0.0.1:44421 -> ::FFFF:127.0.0.1:5222
```
Seeing this, maybe it's just an issue with non detecting IPv4 addresses in IPv6 notation...

**Comment by prefiks** [comment]
This should be fixed by change from 7b5895c90d4c94a52254a0b6c22cb29c31a5742b

**Comment by moneytoo** [comment]
Thanks for a quick fix. This is apparently still not enough for default (and my case) when ejabberd has the IPv4 address in IPv6 notation (as ``::FFFF:127.0.0.1``) and reports "Denied by ACL".

**Comment by prefiks** [comment]
Ok, i added that address in 8c1568ff93a468ab4cc99dd7fb026648bc71e8c9

**Comment by moneytoo** [comment]
Amazing, thanks!
