### ISSUE TITLE
Crash error on Qualys scan 

### ISSUE THREAD

**Issue by brobaniuc** [processone/ejabberd#2217]
> What version of ejabberd are you using?
17.08

> What operating system (version) are you using?
 CPE OS Name: cpe:/o:redhat:enterprise_linux:7.3:GA:server
 Kernel: Linux 3.10.0-514.21.1.el7.x86_64

> How did you install ejabberd (source, package, distribution)?
Package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We have enabled ejabberd_http with mod_http_bind which seems to work fine just that we get this crash each time a Qualys scan is run. The ejabberd instance seems to recover by it self after this crash but I suspect is generating some issues on the existing chat sessions opened at that time which can be removed only by resetting the Mnesia Database on each node. We currently have two ejabberd nodes.
When a Qualys scan is run on the network we get the following crash log:

2018-01-07 02:28:48 =CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.30597.41>
    registered_name: []
    exception throw: {http_request_no_host_header,[{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,272}]},{ejabberd_http,parse_headers,1,[{file,"src/ejabberd_http.erl"},{line,204}]},{ejabberd_http,init,2,[{file,"src/ejabberd_http.erl"},{line,157}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.403.0>,ejabberd_listener,ejabberd_sup,<0.65.0>]
    messages: []
    links: [#Port<0.788204>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 870
  neighbours:

**Comment by zinid** [comment]
The crash is fixed in recent version of ejabberd.

**Comment by brobaniuc** [comment]
We did the update to Ejabberd 17.11 in lower environments and we still get this crash.
By recent version are you referring to 17.12?
Thanks, Bogdan R.

**Comment by zinid** [comment]
This was fixed in e5e64c99f387f667e56399c90a43ed28c39ebed3
So it should be a part of 17.11. Check your installation.

**Comment by brobaniuc** [comment]
Ok thanks, I will try to do the upgrade to 17.12 and check afterwards.

**Comment by zinid** [comment]
I would suggest to wait for 18.01. Several regressions are fixed there.
The release will be today.
