### ISSUE TITLE
cannot start server -  Illegal instruction: 4  "$@" in exec_cmd  

### ISSUE THREAD

**Issue by annjieching** [processone/ejabberd#2230]
> What version of ejabberd are you using?

18.01 on MBA 2011
code in terminal

> What operating system (version) are you using?

macOS High Sierra, 10.13.2 

> How did you install ejabberd (source, package, distribution)?

installer 

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

after fixing the Expat library through brew, I get this following error: 

```
19:00:18.090 [info] Loading configuration from /Applications/ejabberd-18.01/conf/ejabberd.yml
bin/ejabberdctl: line 127: 15239 Illegal instruction: 4  "$@"

```

`15239` changes with every time I tried to run this. 
I cannot comment this out EXEC_CMD function as it appears to be quite essential to the application.  

Thank you!

**Comment by cromain** [comment]
can't reproduce this.
edit ejabberdctl, and add this line at line 2
set -x

then run the script and dump here the output

**Comment by annjieching** [comment]
here: 
[output.txt](https://github.com/processone/ejabberd/files/1639728/output.txt)
thank you!

**Comment by nosnilmot** [comment]
I can reproduce, it appears to be a problem with`/Applications/ejabberd-18.01/lib/darwin-x86_64/libyaml-0.2.dylib` provided by the installer on Mac OS (workaround: delete that file and install libyaml with brew)

Minimal reproducer:
```
$ brew install libyaml
Warning: libyaml 0.1.7 is already installed

$ cat yamltest.c 
#include <yaml.h>
int main()
{
  const char *data = "foo";
  yaml_event_t *event = NULL;
  yaml_parser_t parser;
  yaml_parser_initialize(&parser);
  yaml_parser_set_input_string(&parser, (unsigned char*)data, strlen(data));
  event = malloc(sizeof(yaml_event_t));
  yaml_parser_parse(&parser, event);
  yaml_parser_delete(&parser);
  printf("ok\n");
  return 0;
}

$ cc -lyaml -o yamltest yamltest.c 

# no error with brew's libyaml:
$ ./yamltest 
ok

# illegal instruction with ejabberd's libyaml:
$ DYLD_LIBRARY_PATH=/Applications/ejabberd-18.01/lib/darwin-x86_64 ./yamltest
Illegal instruction: 4
```

**Comment by cromain** [comment]
included libyaml 0.1.7 has been updated and should fix this issue.

**Comment by f055** [comment]
Reopening, as it seems this issue still exists when installing ejabberd 18.04 on High Sierra 10.13.4.

**Comment by cromain** [comment]
@f055 you still have problem with High Sierra or Mojave ?

**Comment by f055** [comment]
@cromain this issue is resolved for me.
