### ISSUE TITLE
Image conversion support gone after updating to 18.12

### ISSUE THREAD

**Issue by mbirth** [processone/ejabberd#2716]
I have been running 18.09 on a Raspberry Pi 3B+. That one was installed via the arm64 binary installer from the ProcessOne page. Today I downloaded the arm64 binary installer for 18.12, installed it, copied my config over and … error.

```
2018-12-11 02:00:05.629 [info] <0.292.0>@gen_mod:start_modules:130 Loading modules for myserver.com
2018-12-11 02:00:06.020 [warning] <0.292.0>@mod_http_upload:mod_opt_type:210 ejabberd is built without image converter support, option 'thumbnail' is ignored
2018-12-11 02:00:06.020 [error] <0.292.0>@gen_mod:module_error:573 Invalid value for option 'thumbnail' of module mod_http_upload: true
2018-12-11 02:00:06.021 [critical] <0.292.0>@gen_mod:maybe_halt_ejabberd:310 ejabberd initialization was aborted because a module start failed.
```

As I found nothing about removing image conversion support / thumbnail generation in the changelog, this is a bug, isn't it?

**Comment by zinid** [comment]
> As I found nothing about removing image conversion support / thumbnail generation in the changelog, this is a bug, isn't it?

This is "a bug" in the installer itself I think.

**Comment by cromain** [comment]
i'll double check this, but i think it's a bug as I used a fresh new arm64 build environment, I think it lacks libgd....

**Comment by cromain** [comment]
this is fixed on the arm build chain

**Comment by mbirth** [comment]
Thanks a lot and Happy Holidays! :tada:

**Comment by mbirth** [comment]
Hate to break it to you, but it seems the problem is back in 19.05 (maybe 19.02 as well - didn't test that).

```
2019-06-06 00:50:56.833 [info] <0.298.0>@gen_mod:start_modules:131 Loading modules for example.org
2019-06-06 00:50:57.249 [warning] <0.298.0>@mod_http_upload:mod_opt_type:211 ejabberd is built without image converter support, option 'thumbnail' is ignored
2019-06-06 00:50:57.250 [error] <0.298.0>@gen_mod:module_error:595 Invalid value for option 'thumbnail' of module mod_http_upload: true
2019-06-06 00:50:57.252 [critical] <0.298.0>@gen_mod:maybe_halt_ejabberd:325 ejabberd initialization was aborted because a module start failed.
```
