### ISSUE TITLE
Support IDNA and non-latin domains in mod_http_upload

### ISSUE THREAD

**Issue by Millesimus** [processone/ejabberd#3519]
## Environment

- ejabberd version: 21.01
- Erlang version: 9.3.3.6

## Bug description

I have an IDN domain (with an umlaut) as host in my ejabberd config. Certificates are issued for the domain in punycode. File upload via mod_http_upload from Conversations 2.9.6 to the internal fileserver would fail with standard configuration, so here is what I tried:

#### 1

```yaml
host: punycode
put_url: @HOST@
comment: Works, but nobody wants JIDs in punycode.
```

#### 2

```yaml
host: unicode
put_url: punycode
```

#### 1

```yaml
host: unicode
put_url: @HOST@
```

#### 2

```yaml
host: unicode
put_url: unicode
```

In the failing cases, ejabberd logs that it cannot handle a put request to the host (written in punycode). From the discussion in the Conversations MUC i assume that while Conversations sends http headers (correctly) with punycode, ejabberd should transform them to unicode when interpreting them as host.

**Comment by mrusme** [comment]
Sorry to resurface this old issue, yet I figured that it might be better than creating a new one, given that this is still open.

I'm dealing with a similar situation right now, and I lack clarity on what the convention is.

The author of _Conversations_ [is suggesting](https://codeberg.org/iNPUTmice/Conversations/issues/632#issuecomment-5907937) that I should configure my virtual host using the Unicode domain name. However, the convention in most other areas that I've touched so far ([e.g. web servers](https://nginx.org/en/docs/http/server_names.html#idn)) is to configure the ASCII (punycode) domain. I cannot seem to find any RFC/spec with a definitive answer and I don't think that Ejabberd is supposed to deal with the Unicode virtual host, so I'm tempted to guess that the way IDNs are supposed to be configured on XMPP is via ASCII punycode (`xn--...`).

However, I would appreciate to hear the Ejabberd team's opinions on this. It is in some way _urgent_, as it appears that the _Conversations_ client is going to enforce using the Unicode variant, and thereby possibly break compatibility with Ejabberd.

Thank you.

**Comment by toastal** [comment]
I want to say I used Punycode in the past, but it isn’t ideal as a user since Punycode is unreadable so it’s hard to follow your own configuration. At least the format isn’t JSON else you couldn’t even leave a comment to help yourself.

**Comment by badlop** [comment]
XMPP uses Unicode, and ejabberd does, and all other XMPP software. If something in ejabberd fails when using unicode, then it's a bug, or a misfeature, or unsupported (that should be documented to avoid confusion).

In the case of this issue, I would say the correct configuration are the ones marked as Working 2, Failing 1 and Failing 2, as they use unicode. If they provoke an error in mod_http_upload, the there may be a bug in mod_http_upload, or an internal library called by mod_http_upload.

**Comment by mrusme** [comment]
@badlop thank you for the reply! Just to make it clear, you're saying that...

**This is correct:**

```yml
hosts:
  - "マリウス.com"
```

**This is incorrect:**

```yml
hosts:
  - "xn--gckvb8fzb.com"
```

Right?

**Comment by badlop** [comment]
For `hosts` yes. Try setting the host using unicode, and all in ejabberd will work correctly, login with clients, visit the WebAdmin... 

Except `mod_http_upload` which fails:
```
2025-07-21 18:25:23.836256+02:00 [critical] Failed to start ejabberd application:
 Invalid value of option modules->mod_http_upload->put_url:
 Invalid URL: https://locÃ¤lhost:5443/upload
```

Let's see what to set in the `put_url` option.

In `mod_http_upload`, the option `put_url` is an url. When loading the configuration, `econf` in ejabberd calls the `yconf` library to verify it's a valid URL, and that calls [uri_string:parse](https://www.erlang.org/doc/apps/stdlib/uri_string.html#parse/1) which fails:

```
$ erl
Erlang/OTP 28 [erts-16.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Eshell V16.0.2 (press Ctrl+G to abort, type help(). for help)
1> uri_string:parse(<<"https://locälhost:5443/upload"/utf8>>).
{error,invalid_uri,":"}
```

**Comment by mrusme** [comment]
Just to reiterate what I wrote on the Conversations issue on Codeberg:

> To me personally this sounds like a very bad idea, given that this is not how the rest of the web works. Browsers might display Unicode, yet they will send the ASCII punycode in the background. Similarly I believe that XMPP client applications should at most display Unicode, but always work with ASCII punycode behind the curtain. After all, DNS does not support unicode natively and has to rely on ASCII punycode for that matter.

My _natural instinct_ tells me that the configuration of Ejabberd should be:

```yml
hosts:
  - "xn--gckvb8fzb.com"
```

With that, Ejabberd should be able to resolve any request towards the Unicode domain (`マリウス.com`) and map it to this virtual host, just the way web servers, [mail servers](https://mailing.postfix.users.narkive.com/chCxfrSe/idn-domain-name-support) and DNS servers work.

So I would argue that the IDN topic in Ejabberd is three-fold: 

- First, the way it should be configured, which again, I feel should be by its ASCII punycode rather than its Unicode domain.
- Second, the way IDNs are _seen_ by Ejabberd, which I feel should be as the exact same virtual host, regardless of their representation
- Third, the way requests happen on-the-wire and how they are being translated, which I feel should stick to the way the rest of the web has already established it, with the Unicode domain being an optional representation and the ASCII punycode being the on-the-wire format.

Having that said, @iNPUTmice has kindly linked the following snippet from [RFC6122](https://www.rfc-editor.org/rfc/rfc6122.html):

> Although XMPP applications
> do not communicate the output of the ToASCII operation (called an
> "ACE label") over the wire, it MUST be possible to apply that
> operation without failing to each internationalized label. If an
> XMPP application receives as input an ACE label, it SHOULD convert
> that ACE label to an internationalized label using the ToUnicode
> operation (see [IDNA2003]) before including the label in an XMPP
> domainpart that will be communicated over the wire on an XMPP network

This, indeed suggests that for XMPP's on-the-wire communication the Unicode domain is to be used, which invalidates my third point. Regardless of this, I believe that my first and second point still stand:

If the virtual host `xn--gckvb8fzb.com` was configured for Ejabberd and a request towards `user@マリウス.com` is being received, Ejabberd **should** map that request to the virtual host `xn--gckvb8fzb.com`. Either this, or the other way around -- however, configuring a virtual host using `マリウス.com` clearly causes issues with other modules (see above), which don't occur when the punycode is being used. I had tested the configuration of Unicode domains previously and I experienced similar issues:

```
2025-07-18 14:54:16.010693+00:00 [error] <0.14048.0>@ejabberd_config:reload/0:125 Configuration reload aborted: Exception occurred during configuration processing. This is most likely due to faulty/incompatible validator in third-party code. If you are not running any third-party code, please report the bug with ejabberd configuration file attached and the following stacktrace included:
** exception error: bad argument
   in function  atom_to_binary/2
      called as atom_to_binary('https://\x{30DE}\x{30EA}\x{30A6}\x{30B9}.com:5443/upload',
                               latin1)
      *** argument 1: contains a character not expressible in latin1
   in call from yconf:to_binary/1 (src/yconf.erl, line 978)
   in call from yconf:'-url/1-fun-0-'/2 (src/yconf.erl, line 363)
   in call from yconf:validate_option/3 (src/yconf.erl, line 1261)
   in call from yconf:validate_options/8 (src/yconf.erl, line 1238)
   in call from yconf:'-and_then/2-fun-0-'/3 (src/yconf.erl, line 617)
   in call from yconf:validate_option/3 (src/yconf.erl, line 1261)
   in call from yconf:validate_options/8 (src/yconf.erl, line 1238)
2025-07-18 14:54:32.637223+00:00 [error] <0.14055.0>@ejabberd_config:reload/0:125 Configuration reload aborted: Exception occurred during configuration processing. This is most likely due to faulty/incompatible validator in third-party code. If you are not running any third-party code, please report the bug with ejabberd configuration file attached and the following stacktrace included:
** exception error: bad argument
   in function  atom_to_binary/2
      called as atom_to_binary('https://\x{30DE}\x{30EA}\x{30A6}\x{30B9}.com:5443/upload',
                               latin1)
      *** argument 1: contains a character not expressible in latin1
   in call from yconf:to_binary/1 (src/yconf.erl, line 978)
   in call from yconf:'-url/1-fun-0-'/2 (src/yconf.erl, line 363)
   in call from yconf:validate_option/3 (src/yconf.erl, line 1261)
   in call from yconf:validate_options/8 (src/yconf.erl, line 1238)
   in call from yconf:'-and_then/2-fun-0-'/3 (src/yconf.erl, line 617)
   in call from yconf:validate_option/3 (src/yconf.erl, line 1261)
   in call from yconf:validate_options/8 (src/yconf.erl, line 1238)
2025-07-18 14:56:43.480550+00:00 [critical] <0.14068.0>@ejabberd:exit_or_halt/2:155 Failed to start Erlang application 'odbc': no such file or directory: odbc.app. This usually means that ejabberd or Erlang was compiled/installed incorrectly.
2025-07-18 14:56:43.480795+00:00 [error] <0.14068.0>@ejabberd_hooks:safe_apply/4:460 Hook host_up crashed when running ejabberd_sql_sup:start/1:
** exception error: application_start_failed
   in function  ejabberd:exit_or_halt/2 (src/ejabberd.erl, line 160)
   in call from ejabberd_sql_sup:start/1 (src/ejabberd_sql_sup.erl, line 51)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 456)
   in call from ejabberd_hooks:run1/3 (src/ejabberd_hooks.erl, line 389)
   in call from lists:foreach_1/2 (lists.erl, line 1686)
   in call from ejabberd_config:reload/0 (src/ejabberd_config.erl, line 110)
   in call from ejabberd_admin:reload_config/0 (src/ejabberd_admin.erl, line 850)
   in call from ejabberd_ctl:call_command/4 (src/ejabberd_ctl.erl, line 358)
** Arg 1 = <<227,131,158,227,131,170,227,130,166,227,130,185,46,99,111,109>>
2025-07-18 14:59:39.936692+00:00 [critical] <0.14117.0>@ejabberd:exit_or_halt/2:155 Failed to start Erlang application 'odbc': no such file or directory: odbc.app. This usually means that ejabberd or Erlang was compiled/installed incorrectly.
2025-07-18 14:59:39.937004+00:00 [error] <0.14117.0>@ejabberd_hooks:safe_apply/4:460 Hook host_up crashed when running ejabberd_sql_sup:start/1:
** exception error: application_start_failed
   in function  ejabberd:exit_or_halt/2 (src/ejabberd.erl, line 160)
   in call from ejabberd_sql_sup:start/1 (src/ejabberd_sql_sup.erl, line 51)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 456)
   in call from ejabberd_hooks:run1/3 (src/ejabberd_hooks.erl, line 389)
   in call from lists:foreach_1/2 (lists.erl, line 1686)
   in call from ejabberd_config:reload/0 (src/ejabberd_config.erl, line 110)
   in call from ejabberd_admin:reload_config/0 (src/ejabberd_admin.erl, line 850)
   in call from ejabberd_ctl:call_command/4 (src/ejabberd_ctl.erl, line 358)
** Arg 1 = <<227,131,158,227,131,170,227,130,166,227,130,185,46,99,111,109>>
```

**Comment by badlop** [comment]
> configuring a virtual host using マリウス.com clearly causes issues with other modules (see above)

All those errors seem related to mod_http_upload and/or its put_url option. Disable that module and errors disappear right? Then we know where to look at.

**Comment by mrusme** [comment]
@badlop just did and enabled the Unicode domain in addition to the existing Punycode one:

```yml
hosts:
  - "xn--gckvb8fzb.com"
  - "マリウス.com"
```


```
==> /var/log/ejabberd/error.log <==
2025-07-21 16:37:41.117222+00:00 [critical] <0.28718.0>@ejabberd:exit_or_halt/2:155 Failed to start Erlang application 'odbc': no such file or directory: odbc.app. This usually means that ejabberd or Erlang was compiled/installed incorrectly.
2025-07-21 16:37:41.117482+00:00 [error] <0.28718.0>@ejabberd_hooks:safe_apply/4:460 Hook host_up crashed when running ejabberd_sql_sup:start/1:
** exception error: application_start_failed
   in function  ejabberd:exit_or_halt/2 (src/ejabberd.erl, line 160)
   in call from ejabberd_sql_sup:start/1 (src/ejabberd_sql_sup.erl, line 51)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 456)
   in call from ejabberd_hooks:run1/3 (src/ejabberd_hooks.erl, line 389)
   in call from lists:foreach_1/2 (lists.erl, line 1686)
   in call from ejabberd_config:reload/0 (src/ejabberd_config.erl, line 110)
   in call from ejabberd_admin:reload_config/0 (src/ejabberd_admin.erl, line 850)
   in call from ejabberd_ctl:call_command/4 (src/ejabberd_ctl.erl, line 358)
** Arg 1 = <<227,131,158,227,131,170,227,130,166,227,130,185,46,99,111,109>>

==> /var/log/ejabberd/ejabberd.log <==
2025-07-21 16:37:41.096699+00:00 [info] <0.28718.0>@ejabberd_config:reload/0:103 Reloading configuration from /usr/local/etc/ejabberd/ejabberd.yml
2025-07-21 16:37:41.117222+00:00 [critical] <0.28718.0>@ejabberd:exit_or_halt/2:155 Failed to start Erlang application 'odbc': no such file or directory: odbc.app. This usually means that ejabberd or Erlang was compiled/installed incorrectly.
2025-07-21 16:37:41.117482+00:00 [error] <0.28718.0>@ejabberd_hooks:safe_apply/4:460 Hook host_up crashed when running ejabberd_sql_sup:start/1:
** exception error: application_start_failed
   in function  ejabberd:exit_or_halt/2 (src/ejabberd.erl, line 160)
   in call from ejabberd_sql_sup:start/1 (src/ejabberd_sql_sup.erl, line 51)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl, line 456)
   in call from ejabberd_hooks:run1/3 (src/ejabberd_hooks.erl, line 389)
   in call from lists:foreach_1/2 (lists.erl, line 1686)
   in call from ejabberd_config:reload/0 (src/ejabberd_config.erl, line 110)
   in call from ejabberd_admin:reload_config/0 (src/ejabberd_admin.erl, line 850)
   in call from ejabberd_ctl:call_command/4 (src/ejabberd_ctl.erl, line 358)
** Arg 1 = <<227,131,158,227,131,170,227,130,166,227,130,185,46,99,111,109>>
2025-07-21 16:37:41.119605+00:00 [info] <0.28724.0>@mod_stun_disco:parse_listener/1:618 Going to offer STUN/TURN service: 70.34.209.135:5478 (udp)
2025-07-21 16:37:41.119685+00:00 [info] <0.28724.0>@mod_stun_disco:parse_listener/1:618 Going to offer STUN/TURN service: [2a05:f480:2000:2189:5400:5ff:fe88:34cc]:5478 (udp)
2025-07-21 16:37:41.121380+00:00 [info] <0.28732.0>@ejabberd_s2s_out:init/1:292 Outbound s2s connection started: マリウス.com -> xmppbl.org
2025-07-21 16:37:41.122962+00:00 [info] <0.28718.0>@ejabberd_listener:stop_listener/3:512 Stop accepting TLS connections at [::]:5443 for ejabberd_http
2025-07-21 16:37:41.123311+00:00 [info] <0.28736.0>@ejabberd_listener:init/4:163 Start accepting TLS connections at [::]:5443 for ejabberd_http
2025-07-21 16:37:41.175929+00:00 [info] <0.28718.0>@ejabberd_config:reload/0:123 Configuration reloaded successfully
2025-07-21 16:37:41.458255+00:00 [info] <0.28732.0>@ejabberd_s2s_out:handle_auth_success/2:226 (tls|<0.28732.0>) Accepted outbound s2s EXTERNAL authentication マリウス.com -> xmppbl.org (2001:41d0:701:1100::3b7e)
2025-07-21 16:37:44.904535+00:00 [info] <0.373.0>@ejabberd_listener:accept/7:363 (<0.28739.0>) Accepted connection [2001:41d0:701:1100::3b7e]:35508 -> [2a05:f480:2000:2189:5400:5ff:fe88:34cc]:5269                                                                                    2025-07-21 16:37:44.905022+00:00 [info] <0.28739.0>@ejabberd_s2s_in:process_closed/2:132 Closing inbound s2s connection 2001:41d0:701:1100::3b7e -> xn--gckvb8fzb.com: Stream closed by local host: Bad value of attribute 'from' in tag <stream:stream/> qualified by namespace 'jabber:server' (invalid-xml)
2025-07-21 16:38:13.131697+00:00 [warning] <0.28731.0>@mod_muc_rtbl:parse_initial_items/2:112 Fetching initial list failed: fetch timeout. Retrying in 60 seconds
```

When I remove the Unicode domain and keep the upload module disabled, this is the log output:

```yml
hosts:
  - "xn--gckvb8fzb.com"
  #- "マリウス.com"
```

```
2025-07-21 16:39:21.429970+00:00 [info] <0.28761.0>@ejabberd_config:reload/0:103 Reloading configuration from /usr/local/etc/ejabberd/ejabberd.yml
2025-07-21 16:39:21.491061+00:00 [info] <0.28761.0>@ejabberd_config:reload/0:123 Configuration reloaded successfully
```

**Comment by mrusme** [comment]
Sorry, the errors came from the fact that I had `host_config` for the punycode domain, not for the Unicode domain enabled. This is the log output with both domains and `host_config` enabled:

```
2025-07-21 16:46:26.790548+00:00 [info] <0.28790.0>@ejabberd_config:reload/0:103 Reloading configuration from /usr/local/etc/ejabberd/ejabberd.yml
2025-07-21 16:46:26.811354+00:00 [info] <0.28799.0>@mod_stun_disco:parse_listener/1:618 Going to offer STUN/TURN service: 70.34.209.135:5478 (udp)
2025-07-21 16:46:26.811449+00:00 [info] <0.28799.0>@mod_stun_disco:parse_listener/1:618 Going to offer STUN/TURN service: [2a05:f480:2000:2189:5400:5ff:fe88:34cc]:5478 (udp)
2025-07-21 16:46:26.813330+00:00 [info] <0.28806.0>@ejabberd_s2s_out:init/1:292 Outbound s2s connection started: マリウス.com -> xmppbl.org
2025-07-21 16:46:26.863530+00:00 [info] <0.28790.0>@ejabberd_config:reload/0:123 Configuration reloaded successfully
2025-07-21 16:46:27.182745+00:00 [info] <0.28806.0>@ejabberd_s2s_out:handle_auth_success/2:226 (tls|<0.28806.0>) Accepted outbound s2s EXTERNAL authentication マリウス.com -> xmppbl.org (2001:41d0:701:1100::3b7e)
2025-07-21 16:46:27.317209+00:00 [info] <0.373.0>@ejabberd_listener:accept/7:363 (<0.28812.0>) Accepted connection [2001:41d0:701:1100::3b7e]:35258 -> [2a05:f480:2000:2189:5400:5ff:fe88:34cc]:5269
2025-07-21 16:46:27.441836+00:00 [info] <0.28812.0>@ejabberd_s2s_in:handle_auth_success/4:183 (tls|<0.28812.0>) Accepted inbound s2s EXTERNAL authentication xmppbl.org -> マリウス.com (2001:41d0:701:1100::3b7e)
```

**Comment by mrusme** [comment]
With this setup, Ejabberd now treats what in reality is the exact same domain as two differrent ones:

<img width="840" height="300" alt="Image" src="https://github.com/user-attachments/assets/cfd30ccc-ce03-4d63-998e-48038371290d" />

This is obviously not the intention. It also appears that if I'm now trying to _move_ to the Unicode domain I have to recreate my user as well as the MUC on that domain.

The question is: With only `マリウス.com` configured, will Ejabberd map requests to `user@xn--gckvb8fzb.com` to the user `user@マリウス.com`? Otherwise this is completely pointless. No single person native to the western hemisphere will be able to contact `user@マリウス.com` given the lack of a JIS keyboard.

To summarize: These are not two different domains, hence they should not be treated as two different virtual hosts by Ejabberd. If this is indeed the case, then this is a bug.

**Comment by iNPUTmice** [comment]
> No single person native to the western hemisphere will be able to contact user@マリウス.com given the lack of a JIS keyboard.

That’s why all (most) XMPP client applications will run `toUnicode()` when the user enters (adds to contact list) `user@xn--gckvb8fzb.com`. That allows users to enter the punycode variant. (and/or users could follow a xmpp URI from your website that is already in unicode format)

**Comment by mrusme** [comment]
Thank you, Daniel!

Just to get this right:

XMPP is doing **the exact opposite** of what e.g. web browsers/servers, email clients/servers, DNS clients/servers do? **The XMPP clients always** convert `xn--gckvb8fzb.com` into `マリウス.com` and use this domain _behind the curtains_ (on-the-wire) for everything, instead of **the servers** using `xn--gckvb8fzb.com` and identifying `マリウス.com` as being _the same thing_?

Sorry for being overly explicit here, I'm just trying to make sense of things.

Edit:

> and/or users could follow a xmpp URI from your website that is already in unicode format

Well, see, here's the thing: Most sensible browser configurations will do the exact opposite: They will convert/display any Unicode domain in Punycode to prevent the users from browsing sites that look like [https://pаypal.com](https://pаypal.com). Try it, hover the link.

Edit 2:

Reminder to myself: Buy the domain xn--pypal-4ve.com, create an XMPP account [`support@pаypal.com`](xmpp:support@pаypal.com) and make some money. /scnr

**Comment by iNPUTmice** [comment]
XMPP is a relatively young protocol (compared to email, HTTP and DNS); it has native unicode support. Usernames (localparts) can be unicode too and it would be extremely odd to have usernames support unicode and not domains.

Not everything is "the web".

That’s how the PayPal contact renders in Conversations:

![Image](https://github.com/user-attachments/assets/eb362fba-ddfd-4cea-94fe-52692a83b217)

**Comment by mrusme** [comment]
Update: I joined [the operators room](xmpp:operators@muc.xmpp.org?join) and had an insightful conversation on this topic, which confirmed what Daniel mentioned:

XMPP works with the unicode domain on-the-wire and hence expects the servers to be configured this way. Clients are supposed to do the transformation the way Daniel described it. While it appears to be possible to nevertheless configure a server using the punycode, it is not recommended to do so. This is basically the statement I have not been able to find anywhere outside of the implicit mention within the RFC that Daniel referenced.

Having that said, I nevertheless feel that Ejabberd's implementation is incoherent. First of all, if unicode domains are the convention, Ejabberd should not allow administrators to add punycode virtual hosts. From what I understood, other servers already prevent or at the very least flag this.

Second, it should definitely not be possible to add the same domain as two different virtual hosts by using the punycode and the unicode formats. It's the same domain. So unless anyone can provide a legit use case for why the same domain in two different formats should map to two different virtual hosts, I would argue that this is a bug.

Last but not least, it still seems odd to me that Ejabberd apparently is able to map an SSL certificate issued to `xn--gckvb8fzb.com` for the domain `マリウス.com`, yet seemingly fails to do the same transparent mapping for requests to the punycode domain when the unicode domain was configured. I will test this more in-depth, though.

@Millesimus to go back to your original issue: Unicode it is, with the temporary fix being a manual `host_config` override to use the punycode URL, e.g.:

```yml
host_config:
  "マリウス.com":
    modules:
      mod_http_upload:
        put_url: https://c3.xn--gckvb8fzb.com:5443/upload
```

Edit: Sorry, I have been too optimistic:

```
** Arg 1 = <<227,131,158,227,131,170,227,130,166,227,130,185,46,99,111,109>>
2025-07-21 19:57:13.082778+00:00 [error] <0.29548.0>@mod_http_upload:start/2:133 Multiple virtual hosts can't use a single 'put_url' without the @HOST@ keyword
2025-07-21 19:57:13.082875+00:00 [critical] <0.29548.0>@gen_mod:start_module/4:192 Failed to start module mod_http_upload: {error,{already_started,<0.28866.0>}}
2025-07-21 19:57:13.083153+00:00 [error] <0.29548.0>@ejabberd_hooks:safe_apply/4:460 Hook config_reloaded crashed when running gen_mod:config_reloaded/0:
```

**Comment by iNPUTmice** [comment]
> First of all, if unicode domains are the convention, Ejabberd should not allow administrators to add punycode virtual hosts.

I guess it would be somehow fine to put the punycode representation into the config file but ejabberd should parse that into the unicode representation upon reading the config file. (Similiar to what @mrusme has experienced with the up configuration, I guess)

**Comment by badlop** [comment]
The last 4 commits add some auxiliary functions, also update the yconf library, and adds support in mod_http_upload for non-latin vhosts. I've tested with Gajim 2.3.2 and seems to work perfectly.

Installers are available in https://github.com/processone/ejabberd/actions/runs/16528391352
container in https://github.com/processone/ejabberd/pkgs/container/ejabberd/470808070?tag=master

Some configuration tips:

<details>

Let's host a domain called `日本語`, which is encoded in IDNA as `xn--wgv71a119e`:
```erlang
ejabberdctl live
(ejabberd@localhost)1> idna:encode("日本語").
"xn--wgv71a119e"
```

Add host to file `/etc/hosts`

```
127.0.0.1 xn--wgv71a119e
```

Create a self-signed certificate for host `xn--wgv71a119e` and store in file `jp.pem`. Result contains:

```
        Issuer: CN = xn--wgv71a119e
        Subject: CN = xn--wgv71a119e
```

Configure ejabberd:

```yaml
hosts:
  - 日本語

ca_file: /home/git/ejabberd/_build/relive/conf/ca.pem
certfiles:
  - /home/git/ejabberd/jp.pem # this contains xn--wgv71a119e

modules:
  mod_http_upload:
    put_url: "https://@HOST_URL_ENCODE@:5443/upload"
```

Start ejabberd and register some accounts

```
ejabberdctl register admin  日本語  asd
ejabberdctl register 日1 日本語  asd
ejabberdctl register 日2 日本語  asd
ejabberdctl register user3 日本語  asd
```

Start Gajim 2.3.2 and login to any of those accounts, open a chat window and send a file. Gajim XML console shows:

```xml
<iq xmlns="jabber:client" xml:lang="en" to="user3@日本語/gajim.SQ3FWUST" from="upload.日本語" type="result" id="773e1f36-4c3f-479d-ad78-0653c7230f00">
  <slot xmlns="urn:xmpp:http:upload:0">
    <get url="https://xn--wgv71a119e:5443/upload/64e7da315dd316175560b152398c865c758b0908/O4iuzPkWWkC1VUgd2YLruHTcr0KysxM42sXDdrzK/Makefile" />
    <put url="https://xn--wgv71a119e:5443/upload/64e7da315dd316175560b152398c865c758b0908/O4iuzPkWWkC1VUgd2YLruHTcr0KysxM42sXDdrzK/Makefile" />
</slot>
</iq>
```

Unfortunately, Gajim throws this error when attempting to send a file using an upload service with a self-signed certificate:
`The signing certificate authority is not known`. Related issue https://dev.gajim.org/gajim/gajim/-/issues/11835

<img width="2113" height="1239" alt="Image" src="https://github.com/user-attachments/assets/d873a837-8048-49fa-87bf-0bb1b9491154" />

Later I've setup a FQDN host, obtained signed certificates with ACME, and this time Gajim was able to send the file correctly, and download it.

</details>

**Comment by badlop** [comment]
> While it appears to be possible to nevertheless configure a server using the punycode, it is not recommended to do so. This is basically the statement I have not been able to find anywhere outside of the implicit mention within the RFC that Daniel referenced.

Ok, this should get mentioned in the ejabberd documentation
https://docs.ejabberd.im/admin/configuration/basic/#host-names

Maybe adding a paragraph like this:

```
Notice that unicode is used natively by XMPP, Erlang/OTP, YAML... and ejabberd.
You can setup non-latin host names using utf8, or IDNA/punycode

hosts:
  - localhost1
  - locälhost2
  - xn--loclhost4-x2a
  - 日本語

host_config:
  "locälhost2":
    modules:
      mod_disco: {}
      mod_muc:
        host: "conference3.@HOST@"
  "xn--loclhost4-x2a":
    modules:
      mod_disco: {}
      mod_muc:
        host: "conference4.@HOST@"
```


> if unicode domains are the convention, Ejabberd should not allow administrators to add punycode virtual hosts. From what I understood, other servers already prevent or at the very least flag this.

Well, in fact it was easy to add support for punycode, I've just committed it right now.

In that case, the hostname is converted internally to utf8, to work correctly with all the other parts of ejabberd.


> Second, it should definitely not be possible to add the same domain as two different virtual hosts by using the punycode and the unicode formats. It's the same domain.

Right. Thanks to the support I mentioned earlier, now detection of duplicate hosts works correctly and complains as expected.


> Last but not least, it still seems odd to me that Ejabberd apparently is able to map an SSL certificate issued to xn--gckvb8fzb.com for the domain マリウス.com, yet seemingly fails to do the same transparent mapping for requests to the punycode domain when the unicode domain was configured.

This should work correctly now.

**Comment by mrusme** [comment]
@badlop thank you very much for your work, it is being highly appreciated! As soon as the version lands in FreeBSD I will be able to test it and give feedback.

**Comment by mrusme** [comment]
@badlop After months of waiting 25.10 finally landed in the FreeBSD repos and I was able to upgrade and test. This is my configuration:

```yaml
  mod_http_upload:
    put_url: "https://c3.@HOST_URL_ENCODE@:5443/upload"
    custom_headers:
      "Access-Control-Allow-Origin": "https://c3.@HOST_URL_ENCODE@"
      "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type"
  mod_http_upload_quota:
    max_days: 2
```

Sadly the upload feature still doesn't appear to be working:

```
2025-11-26 11:09:26.617998+00:00 [error] <0.531.0>@gen_server:error_info/8:1391 ** Generic server 'mod_http_upload_c3.%e3%83%9e%e3%83%aa%e3%82%a6%e3%82%b9.com/upload' terminating 
** Last message in was {route,
                           {iq,<<"oc0P7uXXbowe">>,get,<<"en">>,
                               {jid,<<"marius">>,
                                   <<xxx,>>,
                                   <<"Cheogram.EvvXiWT4aw">>,<<"marius">>,
                                   <<xxx,>>,
                                   <<"Cheogram.EvvXiWT4aw">>},
                               {jid,<<>>,
                                   <<xxx,>>,
                                   <<>>,<<>>,
                                   <<xxx,>>,
                                   <<>>},
                               [{xmlel,<<"request">>,
                                    [{<<"xmlns">>,
                                      <<"urn:xmpp:http:upload:0">>},
                                     {<<"size">>,<<"58517">>},
                                     {<<"content-type">>,<<"image/jpeg">>},
                                     {<<"filename">>,
                                      <<"zb2rhgCHLpkSktrKBjN6Zfsq4T41VtdqdPC8C1mKuMhJ6BMi8.jpg">>}],
                                    []}],
                               #{ip => {23,234,100,28}}}}
** When Server state == {state,<<xxx,>>,
                               [<<xxx,>>],
                               <<"HTTP File Upload">>,local,104857600,40,sha1,
                               undefined,undefined,
                               <<"/var/spool/ejabberd/upload">>,
                               <<"https://c3.%E3%83%9E%E3%83%AA%E3%82%A6%E3%82%B9.com:5443/upload">>,
                               <<"https://c3.%E3%83%9E%E3%83%AA%E3%82%A6%E3%82%B9.com:5443/upload">>,
                               undefined,false,
                               [{<<"Access-Control-Allow-Origin">>,
                                 <<"https://c3.%E3%83%9E%E3%83%AA%E3%82%A6%E3%82%B9.com">>},
                                {<<"Access-Control-Allow-Methods">>,
                                 <<"GET,HEAD,PUT,OPTIONS">>},
                                {<<"Access-Control-Allow-Headers">>,
                                 <<"Content-Type">>}],
                               #{},<<>>}
** Reason for termination ==
** {{bad_label,{alabel,"The label \"%E3%83%9E%E3%83%AA%E3%82%A6%E3%82%B9\"  is not a valid A-label: ulabel error={bad_label,\n                                                                                        {context,\n                                                                                         \"Codepoint 37 not allowed ('DISALLOWED') at posion 0 in \\\"%e3%83%9e%e3%83%aa%e3%82%a6%e3%82%b9\\\"\"}}"}},
    [{idna,alabel,1,[{file,"src/idna.erl"},{line,277}]},
     {idna,encode_1,2,[{file,"src/idna.erl"},{line,147}]},
     {mod_http_upload,reencode_url,1,
                      [{file,"src/mod_http_upload.erl"},{line,926}]},
     {mod_http_upload,mk_slot,4,[{file,"src/mod_http_upload.erl"},{line,914}]},
     {mod_http_upload,process_slot_request,6,
                      [{file,"src/mod_http_upload.erl"},{line,789}]},
     {mod_http_upload,handle_info,2,
                      [{file,"src/mod_http_upload.erl"},{line,484}]},
     {gen_server,try_handle_info,3,[{file,"gen_server.erl"},{line,1095}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1183}]}]}
[0m
2025-11-26 11:09:26.619204+00:00 [error] <0.531.0>@proc_lib:crash_report/4:584 CRASH REPORT:
  crasher:
    initial call: mod_http_upload:init/1
    pid: <0.531.0>
    registered_name: 'mod_http_upload_c3.%e3%83%9e%e3%83%aa%e3%82%a6%e3%82%b9.com/upload'
    exception exit: {bad_label,
                        {alabel,
                            "The label \"%E3%83%9E%E3%83%AA%E3%82%A6%E3%82%B9\"  is not a valid A-label: ulabel error={bad_label,\n                                                                                        {context,\n                                                                                         \"Codepoint 37 not allowed ('DISALLOWED') at posion 0 in \\\"%e3%83%9e%e3%83%aa%e3%82%a6%e3%82%b9\\\"\"}}"}}
      in function  idna:alabel/1 (src/idna.erl, line 277)
      in call from idna:encode_1/2 (src/idna.erl, line 147)
      in call from mod_http_upload:reencode_url/1 (src/mod_http_upload.erl, line 926)
      in call from mod_http_upload:mk_slot/4 (src/mod_http_upload.erl, line 914)
      in call from mod_http_upload:process_slot_request/6 (src/mod_http_upload.erl, line 789)
      in call from mod_http_upload:handle_info/2 (src/mod_http_upload.erl, line 484)
      in call from gen_server:try_handle_info/3 (gen_server.erl, line 1095)
      in call from gen_server:handle_msg/6 (gen_server.erl, line 1183)
    ancestors: [ejabberd_gen_mod_sup,ejabberd_sup,<0.126.0>]
    message_queue_len: 0
    messages: []
    links: [<0.506.0>]
    dictionary: [{rand_seed,{#{type => exsss,next => #Fun<rand.0.65977474>,
                                bits => 58,uniform => #Fun<rand.1.65977474>,
                                uniform_n => #Fun<rand.2.65977474>,
                                jump => #Fun<rand.3.65977474>},
                              [48575668540405283|100720841436180502]}}]
    trap_exit: true
    status: running
    heap_size: 10958
    stack_size: 28
    reductions: 87989
  neighbours:
[0m
2025-11-26 11:09:26.623377+00:00 [error] <0.506.0>@supervisor:do_restart/3:756 SUPERVISOR REPORT:
    supervisor: {local,ejabberd_gen_mod_sup}
    errorContext: child_terminated
    reason: {bad_label,{alabel,"The label \"%E3%83%9E%E3%83%AA%E3%82%A6%E3%82%B9\"  is not a valid A-label: ulabel error={bad_label,\n                                                                                        {context,\n                                                                                         \"Codepoint 37 not allowed ('DISALLOWED') at posion 0 in \\\"%e3%83%9e%e3%83%aa%e3%82%a6%e3%82%b9\\\"\"}}"}}
    offender: [{pid,<0.531.0>},
               {id,'mod_http_upload_c3.%e3%83%9e%e3%83%aa%e3%82%a6%e3%82%b9.com/upload'},
               {mfargs,
                   {gen_server,start_link,
                       [{local,
                            'mod_http_upload_c3.%e3%83%9e%e3%83%aa%e3%82%a6%e3%82%b9.com/upload'},
                        mod_http_upload,
                        [<<xxx,>>,
                         #{access => local,name => <<"HTTP File Upload">>,
                           hosts => [],
                           host =>
                               <<xxx,>>,
                           max_size => 104857600,
                           put_url =>
                               <<"https://c3.%E3%83%9E%E3%83%AA%E3%82%A6%E3%82%B9.com:5443/upload">>,
                           custom_headers =>
                               [{<<"Access-Control-Allow-Origin">>,
                                 <<"https://c3.%E3%83%9E%E3%83%AA%E3%82%A6%E3%82%B9.com">>},
                                {<<"Access-Control-Allow-Methods">>,
                                 <<"GET,HEAD,PUT,OPTIONS">>},
                                {<<"Access-Control-Allow-Headers">>,
                                 <<"Content-Type">>}],
                           service_url => undefined,external_secret => <<>>,
                           get_url => undefined,dir_mode => undefined,
                           docroot => <<"@HOME@/upload">>,
                           file_mode => undefined,jid_in_url => sha1,
                           rm_on_unregister => true,secret_length => 40,
                           thumbnail => false,vcard => undefined}],
                        []]}},
               {restart_type,transient},
               {significant,false},
               {shutdown,60000},
               {child_type,worker}]
```

**Comment by badlop** [comment]
Ah right. The problem was introduced when fixing another problem. With the new fix, I tested both IDNA hosts and accented filenames.

Of course it would be great if you can test it in your real scenario. The fix is just a pair of lines in `mod_http_upload.beam` You can apply the patch to ejabberd, compile and copy just this file.

Or, if you tell me exactly what ejabberd source code you are using, and what Erlang version, I can setup a git branch to let Github Actions automatically compile it in a way compatible with your system; then you can download `mod_http_upload.beam` and try in your server.

**Comment by mrusme** [comment]
@badlop thank you kindly for the propmpt reply and fix! I am happy to test, however I was only able to find the `.beam` file:

```sh
c3# ls -la /usr/local/lib/erlang/lib/ejabberd-25.10/ebin/mod_http_upload.beam
-r--r--r--  1 root wheel 103176 Nov  8 05:33 /usr/local/lib/erlang/lib/ejabberd-25.10/ebin/mod_http_upload.beam
```

The FreeBSD 14.3-RELEASE package doesn't come with the corresponding `‎mod_http_upload.erl` source file. 

Would it be possible for me to download the 25.10 release, apply your patch, compile it locally on Linux, and transfer the resulting `.beam` file to the FreeBSD server, or do you think I should compile it on a FreeBSD machine?

**Comment by badlop** [comment]
> Would it be possible for me to download the 25.10 release, apply your patch, compile it locally on Linux, and transfer the resulting `.beam` file to the FreeBSD server, or do you think I should compile it on a FreeBSD machine?

In short: yes. In long: there are three aspects to look:

## Source code

Yes, you can download ejabberd 25.10 source code, apply the small patch, compile and copy mod_http_upload.beam

In fact, looking at the ejabberd git history, the file mod_http_upload.erl has three commits since 25.10, but none of them breaks compatibility with ejabberd 25.10 when using Erlang/OTP 24 or higher. I mean: you can compile ejabberd git master and copy mod_http_upload.beam to your ejabberd 25.10.

## System architecture

The `*.beam` files do not depend on system architecture (like `*.so` files do): you can compile on amd64 Linux and use *.beam files in arm64 FreeBSD.

## Erlang/OTP version

The important dependency to look: compile in the **same Erlang/OTP major version** that will be running the beam file. For example Erlang/OTP 27, or 28. It doesn't matter minor differences like 28.1 to 28.2.

Anyway, if BEAM finds some problem loading your new *.beam file, it will complain at ejabberd start; then you can recover the previous file, and restart.

**Comment by mrusme** [comment]
@badlop thank you for the provided information! I downloaded the 25.10 sources and applied your patch, compiled it locally and replaced the server's `/usr/local/lib/erlang/lib/ejabberd-25.10/ebin/mod_http_upload.beam` with the one I built.

I have tested uploads and can confirm that they are working. Thank you kindly for your support with this! There are no more errors in the logs.
