### ISSUE TITLE
External authentification on SQL server with PHP

### ISSUE THREAD

**Issue by BenJaziaSadok** [processone/ejabberd#509]
I installed Ejabberd 15.03 on a centOS and i want to authentificate my users against external server/SqlServer using PHP script.
in ejabberd.yml i put this:
```
auth_method: external
extauth_program: "php -f /etc/ejabberd-15.03/auth_script.php"
extauth_cache: 600
extauth_instances: 3
```
Here is my script
```
require 'jabber.php';
class Auth extends EjabberdExternalAuth {
    protected function authenticate($user, $server, $password) {
        return true;
    }
    protected function exists($user, $server) {
        return true;
    }
}
$pdo = new PDO('dblib:dbname=DB;host=IP;charset=utf8', 'user', 'pass');
new Auth($pdo, 'auth.log');
```

Jabber.php
```
<?php
date_default_timezone_set('Europe/Paris');
/**
- A class extending EjabberdExternalAuth may optionally implement this interface
- to support additional, non-critical methods for adding and removing users.
  _/
  interface EjabberdExternalAuth_UserManagement {
  /_*
  - Corresponds to `setpass` operation.
    */
    public function setPassword($user, $server, $password);
  
  /**
  - Corresponds to `tryregister` operation.
    _/
    public function register($user, $server, $password);
    /_*
  - Corresponds to `removeuser` operation.
    _/
    public function remove($user, $server);
    /_*
  - Corresponds to `removeuser3` operation.
    */
    public function removeSafely($user, $server, $password);
    }
    abstract class EjabberdExternalAuth {
    private $db     = null;
    private $log    = null;
    private $stdin  = null;
    private $stdout = null;
  
  public static $logLevel = array(LOG_EMERG, LOG_ALERT, LOG_CRIT, LOG_ERR, LOG_WARNING, LOG_INFO, LOG_KERN);
  /**
  - Corresponds to `auth` operation.
    _/
    abstract protected function authenticate($user, $server, $password);
    /_*
  - Corresponds to `isuser` operation.
    */
    abstract protected function exists($user, $server);
    final public function __construct(PDO $db = null, $log = null) {
    set_error_handler(array($this, 'errorHandler'));
    
    $this->db     = $db;
    $this->stdin  = fopen('php://stdin', 'rb');
    $this->stdout = fopen('php://stdout', 'wb');
    if ($log) {
        $this->log = fopen($log, 'a');
    }
    $this->log('Starting auth service...', LOG_INFO);
    try {
        $this->work();
    } catch (Exception $e) {
        $this->log($e->getMessage());
    }
    
    $this->log('Exiting...', LOG_INFO);
    }
  
  final protected function db() {
      return $this->db;
  }
  final private function work() {
      $this->log('Entering event loop...', LOG_INFO);
  
  while (true) {
      try {
  
          $message = $this->read();
          $message = $this->parseMessage($message);
          echo 'parsed';
      } catch (UnexpectedValueException $e) {
          $this->log($e->getMessage());
          echo 'continue';
          continue;
      }
      $this->log('Received message: ' . json_encode($message), LOG_DEBUG);
      var_dump($response);
      $response = false;
      switch ($message['command']) {
          case 'auth' :
              $response = $this->authenticate($message['user'], $message['server'], $message['password']);
              echo '1';
              break;
          case 'isuser' :
              $response = $this->exists($message['user'], $message['server']);
              echo '2';
              break;
      }
  
      if ($this instanceof EjabberdExternalAuth_UserManagement) {
          switch ($message['command']) {
              case 'setpass' :
                  $response = $this->setPassword($message['user'], $message['server'], $message['password']);
                  echo '3';
                  break;
              case 'tryregister' :
                  $response = $this->register($message['user'], $message['server'], $message['password']);
                  echo '4';
                  break;
              case 'removeuser' :
                  $response = $this->remove($message['user'], $message['server']);
                  echo '5';
                  break;
              case 'removeuser3' :
                  $response = $this->removeSafely($message['user'], $message['server'], $message['password']);
                  echo '6';
                  break;
          }
      }
      $this->respond($response);
  }

  }
  final private function read() {
      $length = fgets($this->stdin, 3);
      if (feof($this->stdin)) {
          throw new RuntimeException('Pipe broken');
      }
      $length = current(unpack('n', $length));
      if (!$length) {
          throw new UnexpectedValueException("Invalid length value, won't continue reading");
      }
      $message = fgets($this->stdin, $length + 1);
      return $message;
  }
  final private function parseMessage($message) {
      $message = explode(':', $message, 4);
      if (count($message) < 3) {
          throw new UnexpectedValueException('Message is too short: ' . join(':', $message));
      }
  

  list($command, $user, $server) = $message;
  $password = isset($message[3]) ? $message[3] : null;
  return compact('command', 'user', 'server', 'password');

  }
  final private function respond($status) {
      $message = pack('nn', 2, (int)$status);
      $this->log('Sending response: ' . bin2hex($message), LOG_DEBUG);
      fwrite($this->stdout, $message);
  }
  final protected function log($message, $severity = LOG_ERR) {
      if ($this->log && in_array($severity, self::$logLevel, true)) {
          static $types = array(
              LOG_EMERG   => 'EMERGENCY',
              LOG_ALERT   => 'ALERT',
              LOG_CRIT    => 'CRITICAL',
              LOG_ERR     => 'ERROR',
              LOG_WARNING => 'WARNING',
              LOG_NOTICE  => 'NOTICE',
              LOG_INFO    => 'INFO',
              LOG_DEBUG   => 'DEBUG',
              LOG_KERN    => 'KERNEL'
          );
  

      $message = sprintf('%s <%s> %9s: %s', date('Y-m-d H:i:s'), getmypid(), isset($types[$severity]) ? $types[$severity] : $types[LOG_ERR], $message);
      fwrite($this->log, $message . PHP_EOL);
  }

  }
  
  final protected function errorHandler($errno, $errstr, $errfile, $errline, array $errcontext) {
      $this->log("($errno) $errstr in $errfile on line $errline");
      return false;
  }
  }
```
I'm always getting this error '11:03:31.539 [critical] extauth script has exitted abruptly with reason 'normal'' even the fact that i did not put any custom authentification method.
I seems to be a configuration issue.

**Comment by mremond** [comment]
Any comment on how the issue was solved ?

**Comment by BenJaziaSadok** [comment]
Not solved but i totally change the method.
I make it back unsolved
