### ISSUE TITLE
15.04: set_last fails with reference to mod_last_odbc

### ISSUE THREAD

**Issue by mathiasertl** [processone/ejabberd#595]
When I execute `ejabberdctl set_last`, I get a stack trace with a reference to `mod_last_odbc`:

```
root@titan: ~ $ ejabberdctl set_last testuser jabber.at 1433507610 Registered
Problem 'error undef' occurred executing the command.
Stacktrace: [{mod_last_odbc,store_last_info,
                            ["testuser","jabber.at",1433507610,
                             "Registered"],
                            []},
             {ejabberd_commands,execute_command2,2,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,320}]},
             {ejabberd_ctl,call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,293}]},
             {ejabberd_ctl,try_call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,269}]},
             {ejabberd_ctl,process2,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,218}]},
             {ejabberd_ctl,process,1,
                           [{file,"src/ejabberd_ctl.erl"},{line,203}]},
             {rpc,'-handle_call_call/6-fun-0-',5,
                  [{file,"rpc.erl"},{line,205}]}]
```

I have the simplest possible mod_last config:

```
    mod_last: {}
```

Also when investigating the current config via the webadmin interface, there is no mention of mod_last either.

**Comment by beherit** [comment]
It is already fixed in https://github.com/processone/ejabberd/commit/77e57afae1d3f4f531afa6556b0d3c45f8e1f418 :)

**Comment by zinid** [comment]
@beherit I don't think it's fixed, because the command is trying to call non-existent `mod_last_odbc` module.

**Comment by badlop** [comment]
It got fixed in https://github.com/processone/ejabberd/commit/fa99519f8bc3c73359ab88e7759e1d0c9405c05d
