### ISSUE TITLE
"error function_clause" when converting ejabberd.cfg to yml with convert_to_yaml: 

### ISSUE THREAD

**Issue by cweiske** [processone/ejabberd#803]
When converting my `ejabberd.cfg` file to yaml in ejabberd 15.09, I get an error:

```
$ ejabberdctl convert_to_yaml /tmp/test.cfg /tmp/ejabberd.yml
Problem 'error function_clause' occurred executing the command.
Stacktrace: [{p1_yaml,encode_pair,
                      [inet6,4],
                      [{file,"src/p1_yaml.erl"},{line,135}]},
             {p1_yaml,'-encode/2-lc$^0/1-1-',2,
                      [{file,"src/p1_yaml.erl"},{line,116}]},
             {p1_yaml,'-encode/2-lc$^0/1-1-',2,
                      [{file,"src/p1_yaml.erl"},{line,116}]},
             {p1_yaml,'-encode/2-lc$^1/1-0-',2,
                      [{file,"src/p1_yaml.erl"},{line,118}]},
             {p1_yaml,encode_pair,2,[{file,"src/p1_yaml.erl"},{line,136}]},
             {p1_yaml,'-encode/2-lc$^0/1-1-',2,
                      [{file,"src/p1_yaml.erl"},{line,116}]},
             {p1_yaml,'-encode/2-lc$^0/1-1-',2,
                      [{file,"src/p1_yaml.erl"},{line,116}]},
             {p1_yaml,encode,1,[{file,"src/p1_yaml.erl"},{line,108}]}]
```

The configuration file can be found at http://p.cweiske.de/239

**Comment by zinid** [comment]
Fixed

**Comment by ghenry** [comment]
Hi,
I'm still getting this on 16.02. Any ideas?:

bin/ejabberdctl convert_to_yaml /opt/ejabberd/conf/ejabberd.cfg /tmp/ejabberd.yml

=ERROR REPORT==== 23-Mar-2016::11:29:16 ===
File operation error: eacces. Target: /opt/ejabberd/lib/xmerl-1.3.7/ebin/ejabberd_ctl.beam. Function: get_file. Process: code_server.
Problem 'error function_clause' occurred executing the command.
Stacktrace: [{fast_yaml,encode,
                        [{<<"uid">>},8],
                        [{file,"src/fast_yaml.erl"},{line,109}]},
             {fast_yaml,'-encode/2-lc$^1/1-0-',2,
                        [{file,"src/fast_yaml.erl"},{line,112}]},
             {fast_yaml,encode_pair,2,[{file,"src/fast_yaml.erl"},{line,130}]},
             {fast_yaml,'-encode/2-lc$^0/1-1-',2,
                        [{file,"src/fast_yaml.erl"},{line,110}]},
             {fast_yaml,encode_pair,2,[{file,"src/fast_yaml.erl"},{line,130}]},
             {fast_yaml,'-encode/2-lc$^0/1-1-',2,
                        [{file,"src/fast_yaml.erl"},{line,110}]},
             {fast_yaml,encode_pair,2,[{file,"src/fast_yaml.erl"},{line,130}]},
             {fast_yaml,'-encode/2-lc$^0/1-1-',2,
                        [{file,"src/fast_yaml.erl"},{line,110}]}]

**Comment by zinid** [comment]
Post your configuration somewhere.

**Comment by ghenry** [comment]
Do you except GPG emails somewhere?

**Comment by zinid** [comment]
No, just replace sensitive data and paste it somewhere.

**Comment by ghenry** [comment]
OK, thanks. Here's a cut down version as we do multiple domains:

http://paste.scsys.co.uk/508409

**Comment by ghenry** [comment]
Hi, any news or was this fixed in the 16.03 release?

**Comment by mremond** [comment]
No, not sure what happens in your case. Strange path for example: /opt/ejabberd/lib/xmerl-1.3.7/ebin/ejabberd_ctl.beam

**Comment by ghenry** [comment]
Where do you see /opt/ejabberd/lib/xmerl-1.3.7/ebin/ejabberd_ctl.beam ?

**Comment by mremond** [comment]
In the log you posted:

```
=ERROR REPORT==== 23-Mar-2016::11:29:16 ===
File operation error: eacces. Target: /opt/ejabberd/lib/xmerl-1.3.7/ebin/ejabberd_ctl.beam. Function: get_file. Process: code_server.
```

**Comment by ghenry** [comment]
I installed in /opt/ejabbered so maybe a file permission or missing file?

**Comment by badlop** [comment]
Your log shows two unrelated problems. The first one about ejabberd_ctl.beam, I cannot reproduce it, and I would bet it's a package or installation problem.

The second one about fast_yaml is easy to reproduce and seems a bug in ejabberd or one of its libraries, or a misfeature. How to reproduce:
* Install ejabberd 16.03, or git master
* Create the file /tmp/ejabberd.cfg with a small content like this (extracted from https://github.com/processone/ejabberd/issues/803#issuecomment-200335490 ):
```
{host_config, "ict.example.com", [
    {auth_method, ldap},
    {ldap_servers, ["ldap.example.com"]},
    {ldap_password, "password123"},
    {ldap_uids, [{"uid1"}]}
]}.
```
* Try to convert the file to yaml:
```
$ ejabberdctl convert_to_yaml /tmp/ejabberd2.cfg /tmp/ejabberd2.yml
Problem 'error function_clause' occurred executing the command.
Stacktrace: [{fast_yaml,encode,
                        [{<<"uid1">>},8],
                        [{file,"src/fast_yaml.erl"},{line,109}]},
             {fast_yaml,'-encode/2-lc$^1/1-0-',2,
                        [{file,"src/fast_yaml.erl"},{line,112}]},
             {fast_yaml,encode_pair,2,[{file,"src/fast_yaml.erl"},{line,130}]},
             {fast_yaml,'-encode/2-lc$^0/1-1-',2,
                        [{file,"src/fast_yaml.erl"},{line,110}]},
             {fast_yaml,encode_pair,2,[{file,"src/fast_yaml.erl"},{line,130}]},
             {fast_yaml,'-encode/2-lc$^0/1-1-',2,
                        [{file,"src/fast_yaml.erl"},{line,110}]},
             {fast_yaml,encode_pair,2,[{file,"src/fast_yaml.erl"},{line,130}]},
             {fast_yaml,'-encode/2-lc$^0/1-1-',2,
                        [{file,"src/fast_yaml.erl"},{line,110}]}]
```

**Comment by TiWeiYu** [comment]
i install ejabbed-16.03 with ejabberd-16.03-linux-x86_64-installer.run.
when i set the .yaml file and start the server.

it shown errors on ejabberd.log
=============================
2016-04-13 01:47:39.355 [info] <0.37.0>@ejabberd_app:stop:94 ejabberd 16.03 is stopped in the node ejabberd@localhost
2016-04-13 01:47:41.224 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/error_logger_lager_h.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.224 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/lager_stdlib.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.225 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/lager_trunc_io.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.225 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/lager_format.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.225 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/lager_msg.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.226 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/lager_default_formatter.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.231 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/glc.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.236 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/glc_ops.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.241 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/gr_param.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.248 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/gr_counter.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.254 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/gr_manager.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.260 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/glc_lib.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.266 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/glc_code.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.272 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/erl_syntax.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.280 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/erl_syntax_lib.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.286 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/compile.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.323 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/sys_pre_expand.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.336 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/v3_core.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.350 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/cerl.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.359 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/core_lib.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.365 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/sys_core_fold.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.377 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/cerl_clauses.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.382 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/erl_bifs.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.387 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/sys_core_dsetel.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.393 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/v3_kernel.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.404 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/v3_life.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.412 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/v3_codegen.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.424 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_a.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.429 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_jump.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.435 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_block.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.442 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_utils.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.448 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_clean.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.454 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_except.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.459 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_bool.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.466 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_type.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.473 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_split.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.478 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_dead.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.485 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_peep.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.490 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_bsm.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.497 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_receive.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.503 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_trim.beam. Function: get_file. Process: code_server.
2016-04-13 01:47:41.509 [error] <0.632.0> File operation error: eacces. Target: /opt/ejabberd-16.03/lib/xmerl-1.3.7/ebin/beam_flatten.beam. Function: get_file. Process: code_server.

**Comment by mremond** [comment]
@TiWeiYu Please do not post comment unrelated to the existing issue. This is confusing and is not the best way to get a proper answer. In your case, your installation is messed up, you probably used wrong user to either install and / or launch ejabberd (you have rights problem on the file system).

**Comment by TiWeiYu** [comment]
ok. i have know it.
thanks.
