### ISSUE TITLE
send_message not working

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#878]
Command 'send_message' doesn't work - every time I have and error e.g.:
```
root@test:~# ejabberdctl send_message chat localhost test@localhost \"Hello World\" \"This is just a test.\"
Error: the command "send_message" requires 5 less argument.
  Command Name: send_message
  Arguments: type::binary
             from::binary
             to::binary
             subject::binary
             body::binary
  Returns: res::rescode
  Tags:  stanza
  Description:  Send a message to a local or remote bare of full JID
Error: the command "send_message" requires 5 less argument.
```
A few version earlier everything worked okey.

**Comment by beherit** [comment]
My mistake, everything works:
```
ejabberdctl send_message chat localhost test@localhost "Hello World" "This is just a test."
```
But I have another question - how tu put new line in message?

**Comment by badlop** [comment]
> how tu put new line in message?

I think it isn't possible.

**Comment by mremond** [comment]
> how tu put new line in message?

If you want to format the message precisely, you can always use XHTML formatting: http://www.xmpp.org/extensions/xep-0071.html

**Comment by beherit** [comment]
I need to use only plain text.

**Comment by mremond** [comment]
Ah sorry my comment was more generic about sending message, but not specific to command-line. In that case, I do not think it is possible with ejabberdctl command. I suggest you open a ticket for a feature request if you wish.

**Comment by badlop** [comment]
Formatting of command arguments when using the ejabberdctl frontend is limited by the shell.

You may prefer to use other frontends, for example a XMLRPC client that calls to ejabberd_xmlrpc.

Example client in Python:
```
import xmlrpclib
server_url = 'http://127.0.0.1:4560'
server = xmlrpclib.ServerProxy(server_url, verbose=True)

EJABBERD_XMLRPC_LOGIN = {'user': 'user1', 'server': 'localhost',
                         'password': 'mypass11', 'admin': True}

def ejabberdctl(command, data):
    fn = getattr(server, command)
    return fn(EJABBERD_XMLRPC_LOGIN, data)

result = ejabberdctl('send_message', {
    'type':'chat',
    'from':'localhost',
    'to':'user123@localhost',
    'subject':'Test Message',
    'body':'This is just a test.\nThanks for reading.\nBye'})
print result
```

So, calling that script the user receives this:
```
<message from='localhost'
	to='user123@localhost/tka1'
	type='chat'
	id='3762350208124540931'>
  <body>This is just a test.
Thanks for reading.
Bye</body>
</message>
```

**Comment by prefiks** [comment]
So it looks like my refactor of parsing arguments in ejabberdctl do make it pass invisible chars as \x escape sequences to erlang. I will try to fix this so it will be possible to just use "abc\ndef" as argument and ejabberd will see that new line.

**Comment by prefiks** [comment]
Fixed in 47a67c7320089be64697232ccd218bc3c10ba508

**Comment by beherit** [comment]
@prefiks Thank You for fix but it's doesn't work correctly :(

```
ejabberdctl send_message chat domain.tld test@domain.tld "Test" "Hello World\nTest test.\nBye"
```
And I get:
```
<message from='domain.tld' to='test@domain.tld/Home' type='chat' id='6606942235926228790'>
  <archived by='domain.tld' xmlns='urn:xmpp:mam:tmp' id='1455358445453123'/>
  <stanza-id by='domain.tld' xmlns='urn:xmpp:sid:0' id='1455358445453123'/>
  <body>Hello\ World
Test\ test.
Bye</body>
</message>
```
After every word I have slash character.

**Comment by prefiks** [comment]
I think this should be fixed by commit ab8e374dcd40b34cdd23af1eaf8f0165b82c5bb0. Quoting in sh i real magic...

**Comment by beherit** [comment]
Still doesn't work :( Now I receive to IM a text with \n character.
```
<message from='domain.tld' to='test@domain.tld/Home' type='chat' id='8979774932326661301'>
  <archived by='domain.tld' xmlns='urn:xmpp:mam:tmp' id='1455552253610198'/>
  <stanza-id by='domain.tld' xmlns='urn:xmpp:sid:0' id='1455552253610198'/>
  <body>Hello World\nTest test.\nBye</body>
</message>
```

**Comment by prefiks** [comment]
Please try doing this:

ejabberdctl send_message chat domain.tld test@domain.tld "Test" $'Hello World\nTest test.\nBye'

From my testing \n are not expanded inside ""

**Comment by beherit** [comment]
Not working, It gives the same results.

**Comment by beherit** [comment]
@prefiks the problem is still exist, any chance to fix it?

**Comment by prefiks** [comment]
Can you tell me what shell are you using? It looks like in some shells "abc\ndef" or $'abc\ndef' don't generate new line character but two characters \ and n that ejabberd don't interpret and send as two characters. I was able to get correct result using zsh and bash and $'a\nb' string, not sure if this is something specific to my shell, or it just works in them by default.

You may test what your shell generate using: perl -e 'print $ARGV[0]' $'a\nb' - if this output a <new line> b then it should work with ejabberdctl, if you get a\nb then you would need to find out how to pass new line as argument with your shell (something like this "`printf "a\nb"`" may work)

**Comment by beherit** [comment]
I tested it via FireSSH and there is problem with new lines. Nvm because via mod_rest new lines works :) But I have another problem... Polish characters stopped working via mod_rest :/

**Comment by beherit** [comment]
@prefiks could You take a look in https://github.com/processone/ejabberd-contrib/issues/153 ?

**Comment by beherit** [comment]
Can someone help with resolving this issue?

**Comment by beherit** [comment]
I mean helping with unicode characters.

**Comment by kalabantas** [comment]
Here is how I got it to work in nix
Adding a carriage return
cat /root/scripts/report |sed 's/$/\&#13;\&#10;/g'
This would add a carriage return , replacing the end of each line, and would be displayed correctly in XML

**Comment by meghaParmar** [comment]
Some times I am not getting message id at response. 
Sending message in reference with this : https://docs.ejabberd.im/developer/ejabberd-api/admin-api/
